

# RAILWAY PRICE CHECKER
def get_fare(source, destination):
    fare_prices = {
        ('roosevelt','roosevelt'): ,
        ('roosevelt','balintawak'): ,
        ('roosevelt','monumento'): ,
        ('roosevelt','5th avenue'): ,
        ('roosevelt','r.papa'): ,
        ('roosevelt','abad santos'): ,
        ('roosevelt','blumentrit'): ,
        ('roosevelt','tayuman'): ,
        ('roosevelt','bambang'): ,
        ('roosevelt','doroteo Jose'): ,
        ('roosevelt','carriedo'): ,
        ('roosevelt','central terminal'): ,
        ('roosevelt','united nations'): ,
        ('roosevelt','pedro gil'): ,
        ('roosevelt','quirino'): ,
        ('roosevelt','vito cruz'): ,
        ('roosevelt','gil puyat'): ,
        ('roosevelt','libertad'): ,
        ('roosevelt','edsa'): ,
        ('roosevelt','baclaran'): ,
        ('balintawak','roosevelt'): ,
        ('balintawak','balintawak'): ,
        ('balintawak','monumento'): ,
        ('balintawak','5th avenue'): ,
        ('balintawak','r.papa'): ,
        ('balintawak','abad santos'): ,
        ('balintawak','blumentrit'): ,
        ('balintawak','tayuman'): ,
        ('balintawak','bambang'): ,
        ('balintawak','doroteo Jose'): ,
        ('balintawak','carriedo'): ,
        ('balintawak','central terminal'): ,
        ('balintawak','united nations'): ,
        ('balintawak','pedro gil'): ,
        ('balintawak','quirino'): ,
        ('balintawak','vito cruz'): ,
        ('balintawak','gil puyat'): ,
        ('balintawak','libertad'): ,
        ('balintawak','edsa'): ,
        ('balintawak','baclaran'): ,
        ('monumento','roosevelt'): ,
        ('monumento','balintawak'): ,
        ('monumento','monumento'): ,
        ('monumento','5th avenue'): ,
        ('monumento','r.papa'): ,
        ('monumento','abad santos'): ,
        ('monumento','blumentrit'): ,
        ('monumento','tayuman'): ,
        ('monumento','bambang'): ,
        ('monumento','doroteo Jose'): ,
        ('monumento','carriedo'): ,
        ('monumento','central terminal'): ,
        ('monumento','united nations'): ,
        ('monumento','pedro gil'): ,
        ('monumento','quirino'): ,
        ('monumento','vito cruz'): ,
        ('monumento','gil puyat'): ,
        ('monumento','libertad'): ,
        ('monumento','edsa'): ,
        ('monumento','baclaran'): ,
        ('5th avenue','roosevelt'): ,
        ('5th avenue','balintawak'): ,
        ('5th avenue','monumento'): ,
        ('5th avenue','5th avenue'): ,
        ('5th avenue','r.papa'): ,
        ('5th avenue','abad santos'): ,
        ('5th avenue','blumentrit'): ,
        ('5th avenue','tayuman'): ,
        ('5th avenue','bambang'): ,
        ('5th avenue','doroteo Jose'): ,
        ('5th avenue','carriedo'): ,
        ('5th avenue','central terminal'): ,
        ('5th avenue','united nations'): ,
        ('5th avenue','pedro gil'): ,
        ('5th avenue','quirino'): ,
        ('5th avenue','vito cruz'): ,
        ('5th avenue','gil puyat'): ,
        ('5th avenue','libertad'): ,
        ('5th avenue','edsa'): ,
        ('5th avenue','baclaran'): ,
        ('r.papa','roosevelt'): ,
        ('r.papa','balintawak'): ,
        ('r.papa','monumento'): ,
        ('r.papa','5th avenue'): ,
        ('r.papa','r.papa'): ,
        ('r.papa','abad santos'): ,
        ('r.papa','blumentrit'): ,
        ('r.papa','tayuman'): ,
        ('r.papa','bambang'): ,
        ('r.papa','doroteo Jose'): ,
        ('r.papa','carriedo'): ,
        ('r.papa','central terminal'): ,
        ('r.papa','united nations'): ,
        ('r.papa','pedro gil'): ,
        ('r.papa','quirino'): ,
        ('r.papa','vito cruz'): ,
        ('r.papa','gil puyat'): ,
        ('r.papa','libertad'): ,
        ('r.papa','edsa'): ,
        ('r.papa','baclaran'): ,
        ('abad santos','roosevelt'): ,
        ('abad santos','balintawak'): ,
        ('abad santos','monumento'): ,
        ('abad santos','5th avenue'): ,
        ('abad santos','r.papa'): ,
        ('abad santos','abad santos'): ,
        ('abad santos','blumentrit'): ,
        ('abad santos','tayuman'): ,
        ('abad santos','bambang'): ,
        ('abad santos','doroteo Jose'): ,
        ('abad santos','carriedo'): ,
        ('abad santos','central terminal'): ,
        ('abad santos','united nations'): ,
        ('abad santos','pedro gil'): ,
        ('abad santos','quirino'): ,
        ('abad santos','vito cruz'): ,
        ('abad santos','gil puyat'): ,
        ('abad santos','libertad'): ,
        ('abad santos','edsa'): ,
        ('abad santos','baclaran'): ,
        ('blumentrit','roosevelt'): ,
        ('blumentrit','balintawak'): ,
        ('blumentrit','monumento'): ,
        ('blumentrit','5th avenue'): ,
        ('blumentrit','r.papa'): ,
        ('blumentrit','abad santos'): ,
        ('blumentrit','blumentrit'): ,
        ('blumentrit','tayuman'): ,
        ('blumentrit','bambang'): ,
        ('blumentrit','doroteo Jose'): ,
        ('blumentrit','carriedo'): ,
        ('blumentrit','central terminal'): ,
        ('blumentrit','united nations'): ,
        ('blumentrit','pedro gil'): ,
        ('blumentrit','quirino'): ,
        ('blumentrit','vito cruz'): ,
        ('blumentrit','gil puyat'): ,
        ('blumentrit','libertad'): ,
        ('blumentrit','edsa'): ,
        ('blumentrit','baclaran'): ,
        ('tayuman','roosevelt'): ,
        ('tayuman','balintawak'): ,
        ('tayuman','monumento'): ,
        ('tayuman','5th avenue'): ,
        ('tayuman','r.papa'): ,
        ('tayuman','abad santos'): ,
        ('tayuman','blumentrit'): ,
        ('tayuman','tayuman'): ,
        ('tayuman','bambang'): ,
        ('tayuman','doroteo Jose'): ,
        ('tayuman','carriedo'): ,
        ('tayuman','central terminal'): ,
        ('tayuman','united nations'): ,
        ('tayuman','pedro gil'): ,
        ('tayuman','quirino'): ,
        ('tayuman','vito cruz'): ,
        ('tayuman','gil puyat'): ,
        ('tayuman','libertad'): ,
        ('tayuman','edsa'): ,
        ('tayuman','baclaran'): ,
        ('bambang','roosevelt'): ,
        ('bambang','balintawak'): ,
        ('bambang','monumento'): ,
        ('bambang','5th avenue'): ,
        ('bambang','r.papa'): ,
        ('bambang','abad santos'): ,
        ('bambang','blumentrit'): ,
        ('bambang','tayuman'): ,
        ('bambang','bambang'): ,
        ('bambang','doroteo Jose'): ,
        ('bambang','carriedo'): ,
        ('bambang','central terminal'): ,
        ('bambang','united nations'): ,
        ('bambang','pedro gil'): ,
        ('bambang','quirino'): ,
        ('bambang','vito cruz'): ,
        ('bambang','gil puyat'): ,
        ('bambang','libertad'): ,
        ('bambang','edsa'): ,
        ('bambang','baclaran'): ,
        ('doroteo Jose','roosevelt'): ,
        ('doroteo Jose','balintawak'): ,
        ('doroteo Jose','monumento'): ,
        ('doroteo Jose','5th avenue'): ,
        ('doroteo Jose','r.papa'): ,
        ('doroteo Jose','abad santos'): ,
        ('doroteo Jose','blumentrit'): ,
        ('doroteo Jose','tayuman'): ,
        ('doroteo Jose','bambang'): ,
        ('doroteo Jose','doroteo Jose'): ,
        ('doroteo Jose','carriedo'): ,
        ('doroteo Jose','central terminal'): ,
        ('doroteo Jose','united nations'): ,
        ('doroteo Jose','pedro gil'): ,
        ('doroteo Jose','quirino'): ,
        ('doroteo Jose','vito cruz'): ,
        ('doroteo Jose','gil puyat'): ,
        ('doroteo Jose','libertad'): ,
        ('doroteo Jose','edsa'): ,
        ('doroteo Jose','baclaran'): ,
        ('carriedo','roosevelt'): ,
        ('carriedo','balintawak'): ,
        ('carriedo','monumento'): ,
        ('carriedo','5th avenue'): ,
        ('carriedo','r.papa'): ,
        ('carriedo','abad santos'): ,
        ('carriedo','blumentrit'): ,
        ('carriedo','tayuman'): ,
        ('carriedo','bambang'): ,
        ('carriedo','doroteo Jose'): ,
        ('carriedo','carriedo'): ,
        ('carriedo','central terminal'): ,
        ('carriedo','united nations'): ,
        ('carriedo','pedro gil'): ,
        ('carriedo','quirino'): ,
        ('carriedo','vito cruz'): ,
        ('carriedo','gil puyat'): ,
        ('carriedo','libertad'): ,
        ('carriedo','edsa'): ,
        ('carriedo','baclaran'): ,
        ('central terminal','roosevelt'): ,
        ('central terminal','balintawak'): ,
        ('central terminal','monumento'): ,
        ('central terminal','5th avenue'): ,
        ('central terminal','r.papa'): ,
        ('central terminal','abad santos'): ,
        ('central terminal','blumentrit'): ,
        ('central terminal','tayuman'): ,
        ('central terminal','bambang'): ,
        ('central terminal','doroteo Jose'): ,
        ('central terminal','carriedo'): ,
        ('central terminal','central terminal'): ,
        ('central terminal','united nations'): ,
        ('central terminal','pedro gil'): ,
        ('central terminal','quirino'): ,
        ('central terminal','vito cruz'): ,
        ('central terminal','gil puyat'): ,
        ('central terminal','libertad'): ,
        ('central terminal','edsa'): ,
        ('central terminal','baclaran'): ,
        ('united nations','roosevelt'): ,
        ('united nations','balintawak'): ,
        ('united nations','monumento'): ,
        ('united nations','5th avenue'): ,
        ('united nations','r.papa'): ,
        ('united nations','abad santos'): ,
        ('united nations','blumentrit'): ,
        ('united nations','tayuman'): ,
        ('united nations','bambang'): ,
        ('united nations','doroteo Jose'): ,
        ('united nations','carriedo'): ,
        ('united nations','central terminal'): ,
        ('united nations','united nations'): ,
        ('united nations','pedro gil'): ,
        ('united nations','quirino'): ,
        ('united nations','vito cruz'): ,
        ('united nations','gil puyat'): ,
        ('united nations','libertad'): ,
        ('united nations','edsa'): ,
        ('united nations','baclaran'): ,
        ('pedro gil','roosevelt'): ,
        ('pedro gil','balintawak'): ,
        ('pedro gil','monumento'): ,
        ('pedro gil','5th avenue'): ,
        ('pedro gil','r.papa'): ,
        ('pedro gil','abad santos'): ,
        ('pedro gil','blumentrit'): ,
        ('pedro gil','tayuman'): ,
        ('pedro gil','bambang'): ,
        ('pedro gil','doroteo Jose'): ,
        ('pedro gil','carriedo'): ,
        ('pedro gil','central terminal'): ,
        ('pedro gil','united nations'): ,
        ('pedro gil','pedro gil'): ,
        ('pedro gil','quirino'): ,
        ('pedro gil','vito cruz'): ,
        ('pedro gil','gil puyat'): ,
        ('pedro gil','libertad'): ,
        ('pedro gil','edsa'): ,
        ('pedro gil','baclaran'): ,
        ('quirino','roosevelt'): ,
        ('quirino','balintawak'): ,
        ('quirino','monumento'): ,
        ('quirino','5th avenue'): ,
        ('quirino','r.papa'): ,
        ('quirino','abad santos'): ,
        ('quirino','blumentrit'): ,
        ('quirino','tayuman'): ,
        ('quirino','bambang'): ,
        ('quirino','doroteo Jose'): ,
        ('quirino','carriedo'): ,
        ('quirino','central terminal'): ,
        ('quirino','united nations'): ,
        ('quirino','pedro gil'): ,
        ('quirino','quirino'): ,
        ('quirino','vito cruz'): ,
        ('quirino','gil puyat'): ,
        ('quirino','libertad'): ,
        ('quirino','edsa'): ,
        ('quirino','baclaran'): ,
        ('vito cruz','roosevelt'): ,
        ('vito cruz','balintawak'): ,
        ('vito cruz','monumento'): ,
        ('vito cruz','5th avenue'): ,
        ('vito cruz','r.papa'): ,
        ('vito cruz','abad santos'): ,
        ('vito cruz','blumentrit'): ,
        ('vito cruz','tayuman'): ,
        ('vito cruz','bambang'): ,
        ('vito cruz','doroteo Jose'): ,
        ('vito cruz','carriedo'): ,
        ('vito cruz','central terminal'): ,
        ('vito cruz','united nations'): ,
        ('vito cruz','pedro gil'): ,
        ('vito cruz','quirino'): ,
        ('vito cruz','vito cruz'): ,
        ('vito cruz','gil puyat'): ,
        ('vito cruz','libertad'): ,
        ('vito cruz','edsa'): ,
        ('vito cruz','baclaran'): ,
        ('gil puyat','roosevelt'): ,
        ('gil puyat','balintawak'): ,
        ('gil puyat','monumento'): ,
        ('gil puyat','5th avenue'): ,
        ('gil puyat','r.papa'): ,
        ('gil puyat','abad santos'): ,
        ('gil puyat','blumentrit'): ,
        ('gil puyat','tayuman'): ,
        ('gil puyat','bambang'): ,
        ('gil puyat','doroteo Jose'): ,
        ('gil puyat','carriedo'): ,
        ('gil puyat','central terminal'): ,
        ('gil puyat','united nations'): ,
        ('gil puyat','pedro gil'): ,
        ('gil puyat','quirino'): ,
        ('gil puyat','vito cruz'): ,
        ('gil puyat','gil puyat'): ,
        ('gil puyat','libertad'): ,
        ('gil puyat','edsa'): ,
        ('gil puyat','baclaran'): ,
        ('libertad','roosevelt'): ,
        ('libertad','balintawak'): ,
        ('libertad','monumento'): ,
        ('libertad','5th avenue'): ,
        ('libertad','r.papa'): ,
        ('libertad','abad santos'): ,
        ('libertad','blumentrit'): ,
        ('libertad','tayuman'): ,
        ('libertad','bambang'): ,
        ('libertad','doroteo Jose'): ,
        ('libertad','carriedo'): ,
        ('libertad','central terminal'): ,
        ('libertad','united nations'): ,
        ('libertad','pedro gil'): ,
        ('libertad','quirino'): ,
        ('libertad','vito cruz'): ,
        ('libertad','gil puyat'): ,
        ('libertad','libertad'): ,
        ('libertad','edsa'): ,
        ('libertad','baclaran'): ,
        ('edsa','roosevelt'): 34,
        ('edsa','balintawak'): 32 ,
        ('edsa','monumento'): 29 ,
        ('edsa','5th avenue'): 28 ,
        ('edsa','r.papa'): 27 ,
        ('edsa','abad santos'): 26 ,
        ('edsa','blumentrit'): 25 ,
        ('edsa','tayuman'): 24 ,
        ('edsa','bambang'): 24 ,
        ('edsa','doroteo Jose'): 23 ,
        ('edsa','carriedo'): 22 ,
        ('edsa','central terminal'): 21 ,
        ('edsa','united nations'): 20 ,
        ('edsa','pedro gil'): 19 ,
        ('edsa','quirino'): 18 ,
        ('edsa','vito cruz'): 17 ,
        ('edsa','gil puyat'): 15 ,
        ('edsa','libertad'): 15,
        ('edsa','edsa'): 13 ,
        ('edsa','baclaran'): 14 ,
        ('baclaran','roosevelt'): 35 ,
        ('baclaran','balintawak'): 33 ,
        ('baclaran','monumento'): 30 ,
        ('baclaran','r.papa'): 28 ,
        ('baclaran','abad santos'): 27 ,
        ('baclaran','blumentrit'): 26 ,
        ('baclaran','tayuman'): 25 ,
        ('baclaran','bambang'): 24 ,
        ('baclaran','doroteo Jose'): 23 ,
        ('baclaran','carriedo'): 22 ,
        ('baclaran','central terminal'): 21 ,
        ('baclaran','united nations'): 20 ,
        ('baclaran','pedro gil'): 19 ,
        ('baclaran','quirino'): 18 ,
        ('baclaran','vito cruz'): 17 ,
        ('baclaran','gil puyat'): 16 ,
        ('baclaran','libertad'): 15 ,
        ('baclaran','edsa'): 14 ,
        ('baclaran','baclaran'): 13
    }


#DROP DOWN MENU FOR WHAT START AND END STATION

# DISPLAY BEEP RATE
# DISPLAY STUDENT AND SENIOR RATE
# DISPALY STANDARD

# MAKE ONE FOR LRT 1
# MAKE ONE FOR LRT 2
# MAKE ONE FOR MRT 3
# MAKE ONE FOR PNR

# COMPARE PRICE TO RAILWAY RATIO
# SHOW SPEED BASED ON PNR AVERAGE
# SHOW SPEED BASED ON LRT AVERAGE
# SHOW SPEED BASED ON MRT AVERAGE
# PORT TO TKINTER

# SHOW POSTS ABOUT WHAT TO DO FROM OTHER PEOPLE IN THE SAME PLACES