# RAILWAY PRICE CHECKER

# DISPLAY BEEP RATE
# DISPLAY STUDENT AND SENIOR RATE
# DISPALY STANDARD

# MAKE ONE FOR LRT 1
# MAKE ONE FOR LRT 2
# MAKE ONE FOR MRT 3
# MAKE ONE FOR PNR

# COMPARE PRICE TO RAILWAY RATIO
# SHOW SPEED BASED ON PNR AVERAGE
# SHOW SPEED BASED ON LRT AVERAGE
# SHOW SPEED BASED ON MRT AVERAGE

# SHOW POSTS ABOUT WHAT TO DO FROM OTHER PEOPLE IN THE SAME PLACES